name: unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.13", "3.12", "3.11", "3.10", "3.9"]
        os: [ubuntu-latest]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: FNiQGB2Lit6mFn3*ohfq9x-mqEq*N3Pu
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: run tests
        env:
          PG_TESTS: "yes"
          PG_USER: postgres
          PG_PASSWORD: FNiQGB2Lit6mFn3*ohfq9x-mqEq*N3Pu
          PG_HOST: localhost
        run: uv run tox

      - name: upload results
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: unit test results (${{ matrix.os }}, Python ${{ matrix.python-version }})
          path: pytest.xml

  publish-test-results:
    name: publish test results
    needs: run-tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    if: always()
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: artifacts
      - name: publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "artifacts/**/*.xml"
